forgedbyus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from products import urls as product_urls
from products import views as product_views
from products.models import Product, Collection
from . import views

product_dict = {
    'queryset': Product.objects.all().order_by('-created'),
    'date_field': 'created',
}
collection_dict = {
    'queryset': Collection.objects.all(),
    'date_field': 'updated',
}

sitemaps = {
    'products': GenericSitemap(product_dict, priority=0.6),
    'collections': GenericSitemap(collection_dict, priority=0.6)
}

urlpatterns = [
    url(r'^$', views.index),
    url(r'^fbu/(?P<product_id>[A-Z0-9]{10})/(?P<slug>[-\w]+)/$', product_views.details, name='product'),
    url(r'^fbu/(?P<product_id>[A-Z0-9]{10})/$', product_views.details, name='product'),

    url(r'^privacy/$', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    url(r'^disclaimer/$', TemplateView.as_view(template_name="disclaimer.html"), name='disclaimer'),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),

    url(r'^search/', include('haystack.urls')),
    url(r'^collections/(?P<slug>[-\w]+)/$', product_views.collection, name='collections'),
    url(r'^products/', include(product_urls)),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

from django.template.base import add_to_builtins
add_to_builtins('forgedbyus.templatetags.product_tags')

products/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^departments/$', views.category_index),
    url(r'^departments/(?P<slug>[-\w]+)/$', views.category, name='category'),
    url(r'^add_asin/', views.add_asin),
    url(r'^add_product/(?P<product_id>[A-Z0-9]{10})/$', views.add_product),
    url(r'^add_collection/$', views.add_collection),

]

products/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from localflavor.us.models import USStateField
from localflavor.us.us_states import US_STATES
from django.db import models

from affiliates.models import Affiliate
from brands.models import Brand

from slugify import slugify as awesome_slugify

import math

def id_generator():
    import random
    import string
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(10))

class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    image = models.ImageField(null=True, blank=True)
    description = models.CharField(max_length=256, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = awesome_slugify(self.name, max_length=settings.SLUG_MAX_LENGTH, to_lower=True)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return 'category', (), {'slug': self.slug}



class Product(models.Model):
    product_id = models.CharField(db_index=True, max_length=13, unique=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)
    affiliate = models.ForeignKey(Affiliate)
    title = models.CharField(max_length=256)
    asin = models.CharField(db_index=True, max_length=10, null=True, blank=True)
    brand = models.ForeignKey(Brand)
    manufacturer = models.CharField(max_length=128, null=True, blank=True)
    state_of_origin = USStateField(blank=True)
    usa_verified = models.BooleanField(default=False)
    short_description = models.TextField()
    description = models.TextField(null=True, blank=True)
    msrp = models.IntegerField(null=True, blank=True)
    current_price = models.IntegerField()
    price_updated = models.DateTimeField(auto_now_add=True)
    detail_views = models.IntegerField(default=0)
    amazon_prime = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    curated = models.BooleanField(default=False)
    image = models.ImageField(blank=True, null=True)
    thumb = models.ImageField(blank=True, null=True)
    sales_rank = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User, null=True)
    features = ArrayField(
        models.CharField(max_length=128, null=True, blank=True),
        null=True, blank=True
    )
    collections = models.ManyToManyField('Collection', blank=True)
    slug = models.SlugField(null=True, blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.product_id:
            self.product_id = id_generator()
        if not self.slug:
            self.slug = awesome_slugify(self.title, max_length=settings.SLUG_MAX_LENGTH, to_lower=True)
        super(Product, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

    def get_amazon_url(self):
        if self.asin:
            return "http://www.amazon.com/dp/%s/?tag=%s" % (self.asin, settings.AWS_ASSOCIATE_TAG)
        else:
            return None

    def get_full_state(self):
        if self.state_of_origin:
            return [x[1] for x in US_STATES if x[0] == self.state_of_origin][0].title()
        else:
            return 'USA'

    def twitter_text(self):
        import urllib
        return urllib.quote_plus("%s by %s - Made in %s. #MadeInAmerica #AmericanMade" % (self.title, self.brand, self.get_full_state()))

    @models.permalink
    def get_absolute_url(self):
        return 'product', (), {'product_id':self.product_id, 'slug': self.slug}

class Collection(models.Model):
    name = models.CharField(max_length=128, unique=True)
    story = models.TextField(null=True)
    parallax = models.ImageField(null=True, blank=True)
    parallax_blurb = models.TextField(null=True)
    banner = models.ImageField(null=True, blank=True)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = awesome_slugify(self.name, max_length=settings.SLUG_MAX_LENGTH, to_lower=True)
        super(Collection, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return 'collections', (), {'slug':self.slug}

    def __unicode__(self):
        return self.name

products/forms.py
from django import forms
from django.forms import ModelForm

from products.models import Product, Collection

class NewAmazonProductForm(forms.Form):
    asin = forms.CharField(label='ASIN')

class ProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('product_id', 'created', 'detail_views', 'sales_rank', 'user')

class CollectionForm(ModelForm):
    class Meta:
        model = Collection
        exclude = ('created', 'updated')

products/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponsePermanentRedirect
from django.shortcuts import render, redirect, get_object_or_404

from products.forms import NewAmazonProductForm, ProductForm, CollectionForm
from products.models import Product, Category, Collection
from products.tasks import update_detail_views
from products import amazon_utils
from slugify import slugify


def index(request):
    pass

def category_index(request):
    categories = Category.objects.all()
    return render(request, 'category_index.html', {'categories':categories})

def category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category, available=True)
    if request.is_ajax():
        template = 'category_page.html'
    else:
        template = 'category.html'
    return render(request, template, {'category':category, 'products':products})

def details(request, product_id, slug=None):
    product = get_object_or_404(Product, product_id=product_id)
    update_detail_views.delay(product.id)

    title = slugify(product.title, max_length=50, separator=' ', capitalize=True)
    if slug is None and product.slug is not None:
        return HttpResponsePermanentRedirect(reverse('products.views.details', args=[product.product_id, product.slug]))
    if slug != product.slug:
        return HttpResponsePermanentRedirect(reverse('products.views.details', args=[product.product_id, product.slug]))
    if request.is_ajax():
        template = 'product_modal_content.html'
    else:
        template = 'details.html'
    return render(request, template, {'product':product, 'title':title})

def collection(request, slug):
    collection = get_object_or_404(Collection, slug=slug)
    return render(request, 'collection.html', {'collection':collection})

@staff_member_required
def add_asin(request):
    if request.method == 'POST':
        form = NewAmazonProductForm(request.POST)
        if form.is_valid():
            product = amazon_utils.get_asin(form.cleaned_data['asin'].strip().upper(), request.user)
            return redirect('products.views.add_product', product_id=product.product_id)
    else:
        form = NewAmazonProductForm()

    return render(request, 'add_asin.html', {'form': form})

@staff_member_required
def add_product(request, product_id=None):
    product = Product.objects.get(product_id=product_id)
    if request.method == 'POST':
        productform = ProductForm(request.POST, instance=product)
        if productform.is_valid():
            product = productform.save()
            return HttpResponseRedirect(product.get_absolute_url())
    else:
        productform = ProductForm(instance=product)
    return render(request, 'add_product.html', {'form': productform})

@staff_member_required
def add_collection(request):
    if request.method == 'POST':
        form = CollectionForm(request.POST)
        if form.is_valid():
            collection = form.save()
            return HttpResponseRedirect(collection.get_absolute_url())
    else:
        form = CollectionForm()
    return render(request, 'add_collection.html', {'form': form})

products/templates/add_asin.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container main-container headerOffset">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-floppy-saved"></i> Add/Edit Part </span></h1>
                <div class="row userInfo">
                    <div class="col-lg-12">
                        <h2 class="block-title-2"> Please do your best to enter quality information </h2>
                        <p class="required"><sup>*</sup> Required field</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-5">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field|add_class:"form-control" }}
                    </div>
                    {% endfor %}
                    <input type="submit" value="Submit" />
                </form>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5">

            </div>
        </div>
    </div>
</div>
<!-- /.main-container -->

<div class="gap"></div>
{% endblock %}

products/templates/add_collection.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container main-container headerOffset">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-floppy-saved"></i> Add/Edit Collection </span></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-5">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field|add_class:"form-control" }}
                    </div>
                    {% endfor %}
                    <input type="submit" value="Submit" />
                </form>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5">

            </div>
        </div>
    </div>
</div>
<!-- /.main-container -->

<div class="gap"></div>
{% endblock %}

products/templates/add_product.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container main-container headerOffset">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-floppy-saved"></i> Add/Edit Part </span></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-5">
                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field|add_class:"form-control" }}
                    </div>
                    {% endfor %}
                    <input type="submit" value="Submit" />
                </form>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5">
                <h2>Title</h2>
                <p>Remove unnecessary words like the product size, color, Made in USA, etc.</p>
                <h2>State of Origin</h2>
                <p>Do your best to figure out what state this was manufactured in</p>
                <h2>Short Description</h2>
                <p>Remove things like the size and color from this field</p>
                <h2>Amazon Prime</h2>
                <p>Click if this product is amazon prime eligibile</p>

            </div>
        </div>
    </div>
</div>
<!-- /.main-container -->

<div class="gap"></div>
{% endblock %}

products/templates/category.html
{% extends 'base.html' %}

{% block dept_active %}
active
{% endblock %}

{% block content %}
<div class="container main-container headerOffset globalPaddingBottom">
    <h3 class="section-title style2 text-center"><span>{{ category.name }}</span></h3>
    {% include 'category_page.html' %}
</div>
{% endblock %}

products/templates/category_index.html
{% extends 'base.html' %}
{% load static %}

{% block dept_active %}
active
{% endblock %}

{% block content %}

<div class="container main-container headerOffset globalPaddingBottom">
    <div class="row featuredPostContainer ">
        <div class="featuredImageLook3">
            {% for c in categories %}
            {% include 'category_item.html' %}
            {% endfor %}
        </div>
        <!--/.featuredImageLook3-->
    </div>
    <!--/.featuredPostContainer-->
</div>
<!-- /main container -->


<div class="parallax-section parallax-image-1">
    <div class="w100 parallax-section-overley">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="parallax-content clearfix">
                        <h1 class="xlarge"> MADE IN AMERICA </h1>
                        <h5 class="parallaxSubtitle"> FORGED BY US </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/.parallax-section-->

{% endblock %}

products/templates/category_item.html
{% load static %}
<div class="col-md-4 col-sm-6 col-xs-6 col-xs-min-12">
    <div class="inner">
        <div class="box-content-overly box-content-overly-white">
            <div class="box-text-table">
                <div class="box-text-cell ">
                    <div class="box-text-cell-inner dark">
                        <h1 class="uppercase">{{ c.name }}</h1>

                        <p>{{ c.description }}</p>
                        <hr class="submini">
                        <a href="{{ c.get_absolute_url }}" class="btn btn-inverse"> SHOP NOW</a></div>
                </div>
            </div>
        </div>
        <!--/.box-content-overly -->
        <div class="img-title"> {{ c.name }}</div>
        <a class="img-block" href="{{ c.get_absolute_url }}">
            {% if c.image %}
            <img class="img-responsive" src="{{ c.image.url }}" alt="img">
            {% else %}
            <img class="img-responsive" src="{% static 'images/look3/2.jpg' %}" alt="img">
            {% endif %}
        </a>
    </div>
</div>

products/templates/category_page.html
{% load endless %}
<div class="container">
    <div class="row xsResponse">
        {% lazy_paginate 24 products %}
        {% for product in products %}
        {% include 'product_item.html' %}
        {% endfor %}
    </div>
</div>

<div class="row">
    <div class="text-center">
            {% show_more "load more products" %}
    </div>
</div>

products/templates/collection.html
{% extends 'base.html' %}
{% load static %}

{% block collection_active %}
active
{% endblock %}

{% block title %}
{{ collection.name }} - USA Made Collections
{% endblock %}

{% block head %}
<meta property="og:url"           content="{{ request.build_absolute_uri }}" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="{{ collection.name }} - Forged By Us" />
<meta property="og:description"   content="{{ collection.story|striptags }}" />
<meta property="og:image"         content="{{ collection.parallax.url }}" />

<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@forgedbyus" />
<meta name="twitter:title" content="{{ collection.name }} - Forged By Us" />
<meta name="twitter:description" content="{{ collection.story|striptags }}" />
<meta name="twitter:image" content="{{ collection.parallax.url }}" />
{% endblock %}

{% block content %}
<!-- Main component call to action -->
<div class="banner">
    <div class="full-container">
        <div class="slider-content">
            <ul id="pager" class="container">
            </ul>
            <span class="prevControl sliderControl"> <i class="fa fa-angle-left fa-3x "></i></span> <span class="nextControl sliderControl"> <i class="fa fa-angle-right fa-3x "></i></span>
            <div class="slider slider-v1" data-cycle-swipe=true data-cycle-prev=".prevControl" data-cycle-next=".nextControl" data-cycle-loader="wait">
                <div class="slider-item slider-item-img1 "
                     data-cycle-pager-template="">
                    <div class="sliderInfo">
                        <div class="container">
                            <div class="col-lg-5 col-md-5 col-sm-5 pull-left sliderText dark alpha80">
                                <div class="inner">
                                    <h1>{{ collection.name }}</h1>

                                    <p>
                                        {{ collection.parallax_blurb }}
                                    </p>
                                    <h1 class="pull-right">FORGED BY US.</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                    <img alt="img" src="{{ collection.parallax.url }}" class="img-responsive parallaximg sliderImg">
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container main-container">
    <div class="row innerPage">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="row userInfo">
                <div class="col-xs-12 col-sm-12">
                    <h1 class="title-big text-center section-title-style2">
                        <span>{{ collection.name }}</span>
                    </h1>
                    <p class="lead">
                        {{ collection.story|safe }}
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Main component call to action -->

    <div class="morePost row featuredPostContainer style2 globalPaddingTop ">
        <div class="col-lg-12">
            <h3 class="boxes-title-1"><span>{{ collection.name }} Items Made in America</span></h3>
        </div>
        <div class="container">
            <div class="row xsResponse">
                {% for product in collection.product_set.all %}
                {% include 'product_item.html' %}
                {% endfor %}
            </div>
            <!-- /.row -->
        </div>
        <!--/.container-->
    </div>

</div>
    <!--/.section-block-->
{% endblock %}

products/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% load more_like_this %}
{% load product_tags %}

{% block head %}
<meta property="og:url"           content="{{ request.build_absolute_uri }}" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="{{ product.title }} Made in {{ product.get_full_state|default:"USA" }} - Forged By Us" />
<meta property="og:description"   content="{{ product.short_description }}. Made in {{ product.get_full_state|default:"USA" }}." />
<meta property="og:image"         content="{{ product.image.url }}" />

<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@forgedbyus" />
<meta name="twitter:title" content="{{ product.title }} Made in {{ product.get_full_state|default:"USA" }} - Forged By Us" />
<meta name="twitter:description" content="{{ product.short_description }}" />
<meta name="twitter:image" content="{{ product.thumb.url }}" />
{% endblock %}

{% block js %}
<script>
function pinIt()
{
  var e = document.createElement('script');
  e.setAttribute('type','text/javascript');
  e.setAttribute('charset','UTF-8');
  e.setAttribute('src','https://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);
  document.body.appendChild(e);
}
</script>
{% endblock %}

{% block title %}{{ product.title }} - Made in {{ product.get_full_state|default:"USA" }}{% endblock %}

{% block content %}
<div class="container main-container headerOffset" vocab="http://schema.org/" typeof="Product">

    <div class="row transitionfix">

        <!-- left column -->
        <div class="col-lg-6 col-md-6 col-sm-6">
            <!-- product Image and Zoom -->

            <div class="col-lg-12 no-padding">
                <img property="image" src="{{ product.image.url }}" alt="{{ product.title }} by {{ product.brand }}. Made in {{ product.get_full_state|default:"USA" }}." class="img-responsive">
            </div>
        </div>
        <!--/ left column end -->


        <!-- right column -->
        <div class="col-lg-6 col-md-6 col-sm-5">

            <h1 property="name" class="product-title"> {{ product.title }}</h1>

            <h3 property="brand" class="product-code">Brand : {{ product.brand }}</h3>
            <h3 class="product-code"><a href="{% url 'products.views.category_index' %}">Departments</a> > <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
            {% if product.collections.all %}
            <h3 class="product-code">Collections:
                {% for c in product.collections.all %}
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>&nbsp;
                {% endfor %}
            </h3>
            {% endif %}
            <div class="rating">
                <p>MADE IN: <strong>{{ product.get_full_state|default:"USA"|upper }}</strong></p>
            </div>
            <div class="product-price">
                <span class="price-sales"> ${{ product.current_price }}</span>
                {% if product.msrp and product.msrp > product.current_price %}
                <span class="price-standard">${{ product.msrp }}</span>
                {% endif %}
            </div>

            <div class="details-description">
                <p property="description"><strong>From {{ product.affiliate.name }}:</strong> <i>{{ product.short_description|safe }}</i></p>
            </div>


            <div class="cart-actions">
                <div class="addto">
                    <a rel="nofollow" target="_blank" href="{{ product.get_amazon_url }}"><button href="{{ product.get_amazon_url }}" class="button btn-cart cart first"
                            title="Add to Cart" type="button">Buy on {{ product.affiliate }}
                    </button>
                    </a>
                    {% if user.is_staff %}
                    <a href="{% url 'products.views.add_product' product.product_id %}" class="link-wishlist wishlist">Edit Product</a>
                    {% endif %}
                </div>

                <div style="clear:both"></div>
                {% if product.amazon_prime %}
                <h3 class="incaps"><i class="fa fa fa-check-circle-o color-in"></i> Amazon Prime Eligible</h3>
                {% endif %}


            </div>
            <!--/.cart-actions-->

            <div class="clear"></div>
            <div class="details-description">
                <p property="description">{{ product.description|render_db }} </p>
            </div>

            <div class="product-tab w100 clearfix">

                <ul class="nav nav-tabs">
                    <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="details">
                            {% for f in product.features %}
                            <li>{{ f }}</li>
                            {% endfor %}

                    </div>

                </div>
                <!-- /.tab content -->

            </div>
            <!--/.product-tab-->

            <div style="clear:both"></div>

            <div class="product-share clearfix">
                <p> SHARE </p>

                <div class="socialIcon">
                    <a href="http://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"><i class="fa fa-facebook"></i></a>
                    <a class="twitter-share-button" href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text={{ product.twitter_text }}" data-size="large"><i class="fa fa-twitter"></i></a>
                    <a href="javascript:pinIt();"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
            <!--/.product-share-->

        </div>
        <!--/ right column end -->

    </div>
    <!--/.row-->

    <div class="row recommended">
        <div class="morePost row featuredPostContainer style2 globalPaddingTop ">
            <h3 class="section-title style2 text-center"><span>You may also like</span></h3>
            <div class="container">
                <div class="row xsResponse">
                    {% more_like_this product as related_products limit 8 %}
                    {% for p in related_products %}
                    {% with p.object as product %}
                    {% include 'product_item.html' %}
                    {% endwith %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--/.SimilarProductSlider-->
    </div>
    <!--/.recommended-->
    <div style="clear:both"></div>
</div>
<!-- /main-container -->
{% endblock %}

products/templates/item_page.html
{% load endless %}
<div class="container">
    <div class="row xsResponse">
        {% lazy_paginate 24 products %}
        {% for product in products %}
        {% include 'product_item.html' %}
        {% endfor %}
    </div>
</div>

<div class="row">

    <div class="text-center">
            {% show_more "load more products" %}
    </div>
</div>

products/templates/product_item.html
<div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
    <div class="product">
        <a class="add-fav tooltipHere" data-toggle="tooltip" data-original-title="Add to Wishlist"
           data-placement="left">
            <i class="glyphicon glyphicon-heart"></i>
        </a>

        <div class="image">
            <div class="quickview">
                <a href="{{ product.get_absolute_url }}" class="btn-quickview">
                    <strong>{{ product.title }}</strong> <br />by {{ product.brand }}
                </a>
            </div>
            <div class="promotion">
                <span class="discount">${{ product.current_price }}</span>
                <span class="new-product"> {{ product.get_full_state|default:"USA"}}</span>
            </div>
            <a href="{{ product.get_absolute_url }}">
                {% if product.thumb %}
                <img src="{{ product.thumb.url }}" alt="{{ product.title }} by {{ product.brand }}. Made in {{ product.get_full_state }}." class="img-product">
                {% endif %}
            </a>
        </div>
        <br />

        <!--<div class="action-control">
            <a rel="nofollow" target="_blank" href="{{ product.get_amazon_url }}" class="btn btn-primary btn-sharp" data-togle="tooltip" title="price as of {{ product.price_updated }}">
                <span class="add2cart" tooltip="test">
                    Check it out
                </span>
            </a>
        </div>-->
    </div>
</div>

products/templates/product_modal.html
<!-- Product Details Modal  -->
<div class="modal fade" id="product-details-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
        <!--/.modal-content-->
    </div>
    <!--/.modal-content-->
</div>
<!-- End Modal -->